name: Automatic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install semantic-release tools
        run: |
          npm install -g semantic-release \
          @semantic-release/git \
          @semantic-release/changelog \
          @semantic-release/github \
          @semantic-release/commit-analyzer \
          @semantic-release/release-notes-generator

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release