name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  lint:

    name: Shell Lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: |
          shellcheck adguard-update
          shellcheck install.sh

  release:

    name: Create Release
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/v')

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            adguard-update
            install.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}