name: CLI Screenshot

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - adguard-update

permissions:
  contents: write

jobs:

  screenshot:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y asciinema nodejs npm
          npm install -g svg-term-cli

      - name: Record CLI
        run: |
          chmod +x adguard-update
          asciinema rec cli.cast -c "./adguard-update --help" -t "AdGuard Home Updater CLI" -y

      - name: Generate SVG
        run: |
          mkdir -p assets
          cat cli.cast | svg-term --out assets/cli-demo.svg

      - name: Commit screenshot
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add assets/cli-demo.svg

          if git diff --cached --quiet; then
            echo "No screenshot changes"
          else
            git commit -m "docs: update CLI screenshot"
            git push
          fi